Improved Finnish and Sami names and Utf-8 support
subalterngames/Not_Constantinople pull request #1
Opened 2018-07-19 02:52 UTC by Herpior

In the provinces.json, some of the provinces tagged Finnish had Swedish or Russian names. Likewise, the provinces tagged "Lappish" had names in Norwegian, Swedish, Finnish and Russian. 
This changes the names in "Lappish" culture to Northern Sami names and the names in Finnish culture to Finnish names. The names that could be translated were translated, a lot more names were added for both languages, and provinces with names that I could not find any translations for were reclassified as "not_lappish" and "not_finnish" to prevent them skewing the results. They should probably be added to some Russian culture but I don't know which.

Utf-8 support is also included to enable proper spellings for Finnish and Sami names and markovify seems to handle unicode just fine. I don't know if there are some more subtle problems that using unicode in the provinces.json could cause, other than that there are names in other languages that use non-ascii characters that are still left with the ascii version of their name and need updating.

2018-07-19 13:28 UTC, subalterngames commented
This is a great addition!!

>provinces with names that I could not find any translations for were reclassified as "not_lappish" and "not_finnish"

Introducing `not_lappish` and `not_finnish` isn't useful for the program. If the original etymology is obscure, it would still be better to pick an early-attested name for these regions.

For example, a Wikipedia suggests many translations for Kandalax:  _"(Russian: Кандала́кша; Finnish: Kantalahti, also Kandalax or Candalax in the old maps; Karelian: Kannanlakši; Skolt Sami: Käddluhtt)"_ 

I don't know much at all about the land or the languages, but would it make sense to pick any of the options listed above, rather than tagging Kandalax as `not_lappish`?

The other option is to replace `not_lappish` and `not_finnish` with `tbd` (other contributors can add to this category)

Also, please update the README with any cultures you have added.

> I don't know if there are some more subtle problems that using unicode in the provinces.json could cause

I think you're right. There's probably no problem. But it's worth testing. Have you tried blending the languages with the existing ASCII names?

2018-07-20 00:08 UTC, Herpior commented
You are right, `not_lappish` and `not_finnish` are definitely not useful tags for the program. 

As you noted, some of the provinces do have names in Finnish, Northern Sami or Skolt Sami that could be used. However, most of the cities only have a Russian name available, at least in wikipedia. Would it make sense to split provinces into two provinces that span the same area spatially, but are in different languages? This would most likely mean adding provinces with 0-1 settlements. provinces.json already has several provinces without settlements so that shouldn't cause problems.

Currently the `lappish` culture covers the area where Northern Sami is used. It could be beneficial to change the tag into `nothern_sami` so that it describes it more accurately, 'Lappish' is also often considered a pejorative.

Most of the provinces and the settlements in them that were tagged `not_finnish` were somewhere in the middle of Russia, with hardly any searchable information. They should probably be added to a Russian culture but I don't know which culture contains the other Russian names. Other locations in Russia are tagged as `samoyed` or `mordvin` but as far as I know, they are minority cultures. Adding random provinces into either does not seem like very good a solution.

Both the cultures I have edited have a decent amount of settlements so moving the excess provinces to `tbd` should not leave them lacking settlement material. How should `tbd` be mentioned in README as it's not exactly a culture?

> Have you tried blending the languages with the existing ASCII names?

I have run the script a few times on different combinations and the output seems fine. There are not that many special characters even in languages that use them so at least the characters in the ASCII range can chain them with the existing names.

2018-07-20 13:42 UTC, subalterngames commented
>Would it make sense to split provinces into two provinces that span the same area spatially, but are in different languages? 

I think that's an excellent approach. It doesn't matter if the program is geographically redundant. Go ahead and make the change.

>Currently the lappish culture covers the area where Northern Sami is used. It could be beneficial to change the tag into nothern_sami so that it describes it more accurately, 'Lappish' is also often considered a pejorative.

That's really good to know. Go ahead and make the change.

> How should tbd be mentioned in README as it's not exactly a culture?

Maybe add something to the bottom of the cultures section like: **Note**: Some provinces/settlements have the culture "tbd" because they were originally categorized incorrectly. If you recognize them, please fork this project and make the change.

2018-07-20 17:37 UTC, subalterngames requested changes

2018-07-20 17:37 UTC, subalterngames commented on provinces.json
> +        "culture": "Norse"
Typo. `Norse` should be `norse`

2018-07-20 17:47 UTC, subalterngames approved these changes

2018-07-20 17:47 UTC, merged